openapi: 3.1.0
info:
  version: 1.0.0
  title: My Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description:
    This is a documentation of My Contacts app
tags:
  # теги, що ви будете використовувати
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-1-5-vfk7.onrender.com
paths:
   /contacts/{contactId}:
    get:
      $ref: "/swagger/paths/contacts/{id}/get.yaml"
      /home/nook/repositorii/nodejs-hw-mongodb-1/swagger/paths/contacts/get.yaml
      # тут будуть посилання на ендпоінти
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
#------------------------------------
      paths:

